default_stages:
- commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
    - id: mixed-line-ending
    - id: detect-private-key
    - id: check-case-conflict
    - id: requirements-txt-fixer
    - id: fix-encoding-pragma
      args: [--remove]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies:
      - flake8-builtins==2.0.1
      - flake8-bandit==4.1.1
      - bandit==1.7.4
      - flake8-annotations-complexity==0.0.7
      - flake8-class-attributes-order==0.1.3
      - flake8-cognitive-complexity==0.1.0

- repo: local
  hooks:
    - id: mypy
      name: mypy
      pass_filenames: false
      language: python
      entry: bash -c 'make types'

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      language_version: python

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: [--py311-plus]

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
    - id: prettier
      exclude: libs/
      types_or: [css, javascript]

- repo: https://github.com/pre-commit/mirrors-fixmyjs
  rev: v2.0.0
  hooks:
    - id: fixmyjs
      exclude: libs/
      args: ['-l', '-c', '.jshintrc']
